// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzGcZcQaV1eip5ukiGer33sabSCmGeyHU',
    appId: '1:347681671939:web:eafee001c8ca08e5993736',
    messagingSenderId: '347681671939',
    projectId: 'lapor-book-be991',
    authDomain: 'lapor-book-be991.firebaseapp.com',
    storageBucket: 'lapor-book-be991.appspot.com',
    measurementId: 'G-TMJNNV42P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGc4pzFsAIuO4dKvCmXhPgcBUobY2iRiM',
    appId: '1:347681671939:android:f513b806d997f0ab993736',
    messagingSenderId: '347681671939',
    projectId: 'lapor-book-be991',
    storageBucket: 'lapor-book-be991.appspot.com',
  );
}
